// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTTa9TuMTe4TAqm4sq3omONXhFfjUwxKI',
    appId: '1:790674254449:web:2d3f1973d3f8802f1a09d0',
    messagingSenderId: '790674254449',
    projectId: 'epharmacy-d2da2',
    authDomain: 'epharmacy-d2da2.firebaseapp.com',
    storageBucket: 'epharmacy-d2da2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7M40Iyi_T6uCKXJfvaZZemuIct2Tqspo',
    appId: '1:790674254449:android:082bd4a8a2a626341a09d0',
    messagingSenderId: '790674254449',
    projectId: 'epharmacy-d2da2',
    storageBucket: 'epharmacy-d2da2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0FThnTjVTINslS7hRksyFRGCnQwkzGdw',
    appId: '1:790674254449:ios:80da6630cac8be331a09d0',
    messagingSenderId: '790674254449',
    projectId: 'epharmacy-d2da2',
    storageBucket: 'epharmacy-d2da2.appspot.com',
    iosClientId: '790674254449-rvspem75gdj5fc6jm8f65jat0jraar8g.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0FThnTjVTINslS7hRksyFRGCnQwkzGdw',
    appId: '1:790674254449:ios:2e8e214cca46f37a1a09d0',
    messagingSenderId: '790674254449',
    projectId: 'epharmacy-d2da2',
    storageBucket: 'epharmacy-d2da2.appspot.com',
    iosClientId: '790674254449-r5ihmenbl15m0nnuhb980k8du7p28ved.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceadmin.RunnerTests',
  );
}
